const fallbackMacro=[["上证指数","--","--"],["恒生指数","--","--"],["纳斯达克","--","--"],["标普500","--","--"],["美元指数","--","--"],["黄金期货","--","--"],["WTI原油","--","--"],["恐慌指数","--","--"]];
const fallbackSectors=["半导体","科技","人工智能","机器人","清洁能源","太阳能","金融","生物科技","医疗","消费","工业","材料","能源","公用事业","房地产"];
const macroGrid=document.querySelector('#macroGrid');let lastPayload=null,running=true;
function renderMacro(items=fallbackMacro){macroGrid.innerHTML=items.map(m=>`<div class="metric-card"><span>${m.name||m[0]}</span><strong>${m.price??m[1]}</strong><b class="${(m.change??0)>=0?'up':'down'}">${m.changeText||m[2]}</b></div>`).join('')}
let currentScope='global';
function renderSectors(period='1d'){const items=lastPayload?.sectors||fallbackSectors.map(name=>({name,change:0}));const factor=period==='5m'?.18:period==='5d'?2.35:1,proxy=lastPayload?.sectorProxyType||'ETF代理';document.querySelector('#sectorGrid').innerHTML=items.map(s=>{const v=s.change*factor,cls=v>.05?'positive':v<-.05?'negative':'neutral';return `<div class="sector ${cls}" title="${s.symbol||''} ${proxy}"><strong>${s.name}</strong><div><b>${s.symbol?`${v>=0?'+':''}${v.toFixed(2)}%`:'--'}</b><small>${s.symbol||'等待数据'} · ${proxy}</small></div></div>`}).join('');document.querySelector('#sectorSource').textContent=`${lastPayload?.sectorLabel||'全球行业'} · ${proxy} · ${items.length}项 · ${lastPayload?.asOf?new Date(lastPayload.asOf).toLocaleTimeString('zh-CN',{hour12:false}):'等待更新'}`;bindSectorClicks()}
function renderLinkage(items=[]){const root=document.querySelector('#linkageList');if(!root)return;root.innerHTML=items.map(x=>`<div class="linkage-row"><div><b>${x.usName}</b><small>${x.usSymbol} ${x.usChange>=0?'+':''}${x.usChange.toFixed(2)}%</small></div><span class="link-arrow">→</span><div class="linked"><b>${x.cnTheme}</b><small>${x.targets}</small></div><strong class="${x.usChange>=0?'up':'down'}">${x.strength}</strong></div>`).join('')}
function renderMovers(items=[]){const root=document.querySelector('#moversList');if(!root)return;root.innerHTML=items.map((x,i)=>`<article class="mover-item"><div class="mover-main"><div><b>${x.name}</b><small>${x.symbol} · $${x.price.toFixed(2)}</small></div><strong class="${x.change>=0?'up':'down'}">${x.change>=0?'+':''}${x.change.toFixed(2)}%</strong><a href="#" data-theme="${x.cnTheme}">${x.cnTheme}</a></div><button class="reason-toggle" aria-expanded="${i===0}">${i===0?'收起':'查看'}异动解释</button><div class="mover-reason ${i===0?'open':''}"><span>模型解释 · 待事实核验</span><p>${x.reason}</p></div></article>`).join('');root.querySelectorAll('.reason-toggle').forEach(btn=>btn.addEventListener('click',()=>{const box=btn.nextElementSibling;box.classList.toggle('open');btn.textContent=box.classList.contains('open')?'收起异动解释':'查看异动解释';btn.setAttribute('aria-expanded',box.classList.contains('open'))}));root.querySelectorAll('a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();showToast(`联动板块：${a.dataset.theme}`)}))}
function drawChart(values=[]){const canvas=document.querySelector('#marketChart'),rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);if(values.length<2)return;const min=Math.min(...values),max=Math.max(...values),pad=5,w=rect.width,h=rect.height,isUp=values.at(-1)>=values[0],color=isUp?'#f0525f':'#26c985';const x=i=>pad+i*(w-pad*2)/(values.length-1),y=v=>pad+((max-v)/(max-min||1))*(h-pad*2);const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,isUp?'rgba(240,82,95,.28)':'rgba(38,201,133,.28)');grad.addColorStop(1,'rgba(8,13,24,0)');ctx.beginPath();values.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.lineTo(x(values.length-1),h);ctx.lineTo(x(0),h);ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.beginPath();values.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();const state=document.querySelector('#chartState');state.textContent=`纳指日内${isUp?'上涨':'下跌'} · ${values.at(-1).toFixed(2)}`;state.className=`chart-label high ${isUp?'up':'down'}`}
async function loadMarket(){if(!running)return;const start=performance.now(),panel=document.querySelector('.sector-panel');panel.classList.add('loading');try{const endpoint=location.hostname.endsWith('github.io')?`data/${currentScope}.json?t=${Date.now()}`:`/api/market?scope=${currentScope}`,res=await fetch(endpoint,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);lastPayload=await res.json();renderMacro(lastPayload.macro);renderSectors(document.querySelector('#periodFilters .active')?.dataset.period||'1d');renderLinkage(lastPayload.linkage);renderMovers(lastPayload.movers);drawChart(lastPayload.chart);const latency=Math.round(performance.now()-start);document.querySelector('#sourceLatency').textContent=`${latency}ms`;document.querySelector('.market-clock .muted').textContent=`网络 ${latency}ms`;document.querySelector('#feedStatus').textContent=lastPayload.stale?'行情缓存':'真实行情';document.querySelector('#completeness').textContent=`${lastPayload.completeness}%`;document.querySelector('#healthProgress').value=lastPayload.completeness}catch(err){document.querySelector('#feedStatus').textContent='行情连接失败';document.querySelector('#sourceLatency').textContent='离线';console.error(err)}finally{panel.classList.remove('loading')}}
renderMacro();renderSectors();loadMarket();setInterval(loadMarket,15000);document.querySelector('#marketDate').textContent=`${new Intl.DateTimeFormat('zh-CN',{dateStyle:'long'}).format(new Date())} · 全球市场接力进行中`;
const news=[["21:42:08","英伟达财报将在美股盘后公布","关联：AI算力、CPO、存储；当前仅提示事件风险，不生成方向判断。","官方日历","official"],["21:36:51","欧洲半导体指数扩大涨幅","与日韩收盘方向一致，跨市场传导强度升至 74%。","多源验证","multi"],["21:31:19","某存储厂商或将上调季度报价","尚未找到公司正式公告，暂不触发买入信号。","待确认","unconfirmed"]];document.querySelector('#newsList').innerHTML=news.map(n=>`<div class="news-item"><time>${n[0]}</time><div><strong>${n[1]}</strong><p>${n[2]}</p></div><span class="verify ${n[4]}">${n[3]}</span></div>`).join('');
function tick(){document.querySelector('#clock').textContent=new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())}setInterval(tick,1000);tick();document.querySelector('#pauseBtn').addEventListener('click',e=>{running=!running;e.currentTarget.textContent=running?'暂停刷新':'继续刷新';if(running)loadMarket()});document.querySelectorAll('#periodFilters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('#periodFilters button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderSectors(btn.dataset.period)}));
document.querySelectorAll('#marketSwitch button').forEach(btn=>btn.addEventListener('click',()=>{if(btn.dataset.scope===currentScope)return;document.querySelectorAll('#marketSwitch button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentScope=btn.dataset.scope;document.querySelector('#sectorSource').textContent='正在切换并更新真实行情…';loadMarket()}));
const dialog=document.querySelector('#tradeDialog'),toast=document.querySelector('#toast'),main=document.querySelector('main');document.querySelector('#addTradeBtn').addEventListener('click',()=>dialog.showModal());document.querySelector('#tradeForm').addEventListener('submit',e=>{if(e.submitter?.value==='save')showToast('已建立交易后跟踪')});function showToast(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2000)}function bindSectorClicks(){document.querySelectorAll('.sector').forEach(c=>c.addEventListener('click',()=>showToast(`${c.querySelector('strong').textContent}：当前使用ETF代理真实涨跌`)))}function switchView(view,label){main.dataset.view=view;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='sectors')renderSectors(document.querySelector('#periodFilters .active')?.dataset.period||'1d');showToast(`已打开「${label}」模块`)}document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view,btn.textContent.trim())));document.querySelector('.text-btn')?.addEventListener('click',()=>switchView('news','资讯'));main.dataset.view='overview';


